local config = require("pix-nvim-study.config")
local functions = require("pix-nvim-study.functions")

describe("functions", function()
	before_each(function()
		config.setup()
	end)
	describe("vim.cmd", function()
		before_each(function()
			vim.print("vim.cmd before_each")
		end)
		it("vim.cmd test aaa == aaa", function()
			assert.equals("aaa", "aaa")
			functions.run_function("vim.cmd")
		end)
	end)
end)
